### ISSUE TITLE
Panic when generating code for `rocksdb::IOStatus`

### ISSUE THREAD

**Issue by metaspace** [google/autocxx#948] opened 2022-03-23 15:46 UTC
Trying to generate code for `rocksdb`, the generator panics with
```text
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WasNotPin', /home/aeh/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-engine-0.17.3/src/conversion/codegen_rs/lifetime.rs:174:66
```

Not sure if I did anything wrong or there is a bug in `autocxx`.

## Expected Behavior
autocxx will generate bindings or bail without panic

## Actual Behavior
autocxx panics

## Steps to Reproduce the Problem

```shell
git clone --depth 1 -b v7.0.2 https://github.com/facebook/rocksdb
git clone -b util-rs https://github.com/metaspace/zenfs rocksdb/plugin/zenfs
cd rocksdb
make -j$(nproc) ROCKSDB_PLUGINS=zenfs DEBUG_LEVEL=0 PREFIX=/tmp/rocks-install install
cd plugin/zenfs/util-rs
PKG_CONFIG_PATH=/tmp/rocks-install/lib/pkgconfig cargo build --lib
```

## Specifications

- Version: autocxx 0.17.3
- Platform: Arch Linux

## Full backtrace
```text
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WasNotPin', /home/aeh/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-engine-0.17.3/src/conversion/codegen_rs/lifetime.rs:174:66
  stack backtrace:
     0:     0x558e340a43bc - std::backtrace_rs::backtrace::libunwind::trace::h91c465e73bf6c785
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x558e340a43bc - std::backtrace_rs::backtrace::trace_unsynchronized::hae9da36f5d58b5f3
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x558e340a43bc - std::sys_common::backtrace::_print_fmt::h7f499fa126a7effb
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:67:5
     3:     0x558e340a43bc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e2b509ce2ce6007
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:46:22
     4:     0x558e340cd13c - core::fmt::write::h753c7571fa063ecb
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/fmt/mod.rs:1168:17
     5:     0x558e3409eb73 - std::io::Write::write_fmt::h2815c0519c99ba09
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/io/mod.rs:1660:15
     6:     0x558e340a6a92 - std::sys_common::backtrace::_print::h64941a6fc8b0ed9b
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:49:5
     7:     0x558e340a6a92 - std::sys_common::backtrace::print::hcf25e43e1a9b0766
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:36:9
     8:     0x558e340a6a92 - std::panicking::default_hook::{{closure}}::h78d3e6cf97fc623d
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:211:50
     9:     0x558e340a6675 - std::panicking::default_hook::hda898f8d3ad1a5ae
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:228:9
    10:     0x558e340a70e3 - std::panicking::rust_panic_with_hook::h1a5ea2d6c23051aa
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:606:17
    11:     0x558e340a6e00 - std::panicking::begin_panic_handler::{{closure}}::h07f549390938b73f
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:502:13
    12:     0x558e340a4864 - std::sys_common::backtrace::__rust_end_short_backtrace::h5ec3758a92cfb00d
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
    13:     0x558e340a6b39 - rust_begin_unwind
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
    14:     0x558e3354abd1 - core::panicking::panic_fmt::h3a79a6a99affe1d5
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
    15:     0x558e3354acc3 - core::result::unwrap_failed::ha0327e3803285d6e
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
    16:     0x558e3374a52c - core::result::Result<T,E>::unwrap::ha6ecf62eeb7eafbe
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1018:23
    17:     0x558e33591862 - autocxx_engine::conversion::codegen_rs::lifetime::add_lifetime_to_all_params::ha67ec4d72b83f5b3
                                 at /home/aeh/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-engine-0.17.3/src/conversion/codegen_rs/lifetime.rs:174:23
    18:     0x558e3358e109 - autocxx_engine::conversion::codegen_rs::fun_codegen::FnGenerator::generate_constructor_impl::h706ea4c4f9f3a2b9
                                 at /home/aeh/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-engine-0.17.3/src/conversion/codegen_rs/fun_codegen.rs:358:13
    19:     0x558e3358a05d - autocxx_engine::conversion::codegen_rs::fun_codegen::gen_function::h3ba5e93cb4c989b3
                                 at /home/aeh/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-engine-0.17.3/src/conversion/codegen_rs/fun_codegen.rs:131:35
    20:     0x558e3370ac4a - autocxx_engine::conversion::codegen_rs::RsCodeGenerator::generate_rs_for_api::h9b754b88b209f0f5
                                 at /home/aeh/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-engine-0.17.3/src/conversion/codegen_rs/mod.rs:483:52
    21:     0x558e33704dda - autocxx_engine::conversion::codegen_rs::RsCodeGenerator::rs_codegen::{{closure}}::had6e8e82bbe4ea6d
                                 at /home/aeh/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-engine-0.17.3/src/conversion/codegen_rs/mod.rs:176:27
    22:     0x558e335c178a - core::iter::adapters::map::map_fold::{{closure}}::h53047166ca738d32
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/iter/adapters/map.rs:84:28
    23:     0x558e336c9459 - core::iter::traits::iterator::Iterator::fold::hb7fb4985d5ea4425
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/iter/traits/iterator.rs:2171:21
    24:     0x558e335cc103 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::hdb8c1dc89673c7bd
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/iter/adapters/map.rs:124:9
    25:     0x558e3364841c - <(ExtendA,ExtendB) as core::iter::traits::collect::Extend<(A,B)>>::extend::hfcc2bc448810d61c
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/iter/traits/collect.rs:410:9
    26:     0x558e335d1e2b - core::iter::traits::iterator::Iterator::unzip::hb6c2603663973aa0
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/iter/traits/iterator.rs:2963:9
    27:     0x558e33703109 - autocxx_engine::conversion::codegen_rs::RsCodeGenerator::rs_codegen::h1e12a9c0d0164a55
                                 at /home/aeh/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-engine-0.17.3/src/conversion/codegen_rs/mod.rs:171:91
    28:     0x558e33702e11 - autocxx_engine::conversion::codegen_rs::RsCodeGenerator::generate_rs_code::h8e2e7e55deb5989c
                                 at /home/aeh/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-engine-0.17.3/src/conversion/codegen_rs/mod.rs:159:9
    29:     0x558e3366221c - autocxx_engine::conversion::BridgeConverter::convert::h2dcf55f0a63e714b
                                 at /home/aeh/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-engine-0.17.3/src/conversion/mod.rs:193:26
    30:     0x558e3359d89c - autocxx_engine::IncludeCppEngine::generate::h2c5ee67bf3621fd9
                                 at /home/aeh/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-engine-0.17.3/src/lib.rs:387:26
    31:     0x558e33666658 - autocxx_engine::parse_file::ParsedFile::resolve_all::h98741bbd116bec93
                                 at /home/aeh/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-engine-0.17.3/src/parse_file.rs:363:13
    32:     0x558e335561b6 - autocxx_engine::builder::Builder<CTX>::build_listing_files::h9492150105f50f60
                                 at /home/aeh/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-engine-0.17.3/src/builder.rs:224:9
    33:     0x558e33555364 - autocxx_engine::builder::Builder<CTX>::build::h9c3c72849428403c
                                 at /home/aeh/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-engine-0.17.3/src/builder.rs:186:9
    34:     0x558e33557af4 - autocxx_engine::builder::Builder<CTX>::expect_build::h7812274af58bafcf
                                 at /home/aeh/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-engine-0.17.3/src/builder.rs:273:9
    35:     0x558e335529b3 - build_script_build::main::h601d0d0277b10404
                                 at /home/aeh/src/rocksdb/plugin/zenfs/util-rs/build.rs:7:23
    36:     0x558e3354f43b - core::ops::function::FnOnce::call_once::hba2070e34ead54e4
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
    37:     0x558e33553afe - std::sys_common::backtrace::__rust_begin_short_backtrace::h639bb91a661daa76
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:123:18
    38:     0x558e33553ad1 - std::rt::lang_start::{{closure}}::hd9e57318aed930da
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:145:18
    39:     0x558e340a3a70 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h443f738a8e9f947a
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:259:13
    40:     0x558e340a3a70 - std::panicking::try::do_call::h1e21ba261ba489ec
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
    41:     0x558e340a3a70 - std::panicking::try::h6afd48af8b6c96ac
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
    42:     0x558e340a3a70 - std::panic::catch_unwind::h85dd95e0bab7fb60
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
    43:     0x558e340a3a70 - std::rt::lang_start_internal::{{closure}}::h038455e697c8b03e
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:48
    44:     0x558e340a3a70 - std::panicking::try::do_call::h6b0ad65979f3077a
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
    45:     0x558e340a3a70 - std::panicking::try::h010108d314169ac6
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
    46:     0x558e340a3a70 - std::panic::catch_unwind::hff397f912b1535c2
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
    47:     0x558e340a3a70 - std::rt::lang_start_internal::h52e73755f77c7dd9
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:20
    48:     0x558e33553aa0 - std::rt::lang_start::h8daabe4eb1a77502
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:144:17
    49:     0x558e335531bc - main
    50:     0x7ff0189aa310 - __libc_start_call_main
    51:     0x7ff0189aa3c1 - __libc_start_main@GLIBC_2.2.5
    52:     0x558e3354b365 - _start
    53:                0x0 - <unknown>
```

**Comment by adetaylor** [comment] 2022-03-23 16:06
Almost certainly a duplicate of #936 which I fixed yesterday but haven't yet released.

**Comment by adetaylor** [comment] 2022-03-23 16:06
In fact I'll assume so and close this, but please do let me know if that turns out not to be the case.

**Closed by adetaylor** 2022-03-23 16:06 UTC
