### ISSUE TITLE
Feature request: some way to safely handle types aliased in C++

### ISSUE THREAD

**Issue by bsilver8192** [google/autocxx#1146] opened 2022-08-09 06:55 UTC
I'm pretty sure that the current wrapper for `X::is_global` for this type is not callable without undefined behavior:
```c++
class X;
X *global_x = nullptr;
class X {
    X() {
        if (global_x == nullptr) {
            global_x = this;
        }
    }
    ~X() {
        if (global_x == this) {
            global_x = nullptr;
        }
    }
    bool is_global() { return global_x == this; }
};
```
autocxx ends up generating a `fn is_global(self: Pin<&mut Self>) -> bool`. In order to call that, Rust must create a unique reference. The exact details of Rust's aliasing rules are still under discussion, but I'm pretty sure this violates all of the proposals: C++ has a reference to the object which is not derived from the Rust unique reference, and it is used during the unique reference's lifetime.

I would like a nice way to handle types like this. I think manually telling `generate!` to do something different is fine, either with a new name (`generate_by_pointer!` maybe?) or further arguments to it.

My actual example does some bookkeeping in the C++ code (and has assertions that validate the C++ objects are destroyed in order to avoid dangling references), rather than something trivial like this. I'm already writing a Rust newtype to tweak the types (wrap them in alternative Rust types, reshuffle lifetimes, add some hand-written wrappers, convert Rust closures to C++ functors, etc), so a usable but un-ergonomic Rust API would be fine.

Generating `unsafe fn is_global(self: *mut Self) -> bool` would be ideal, but Rust doesn't allow pointers as method receivers, even with `unsafe`. Generating Rust associated functions like `unsafe fn is_global(this: *mut Self) -> bool` is the best alternative that comes to mind, but that's kind of confusing to use.

For now I'm going to work around this by not calling any of the autocxx-generated methods. I'm going to write C++ functions like `bool XIsGlobal(X *);` and use autocxx to wrap those, so at least I only have to write each signature twice (instead of three times like cxx without autocxx).

**Comment by bsilver8192** [comment] 2022-08-12 06:35
Another consideration: `unique_ptr`/`UniquePtr` has this same issue too.

Another workaround, which I'm finding helpful: write a C++ wrapper that has the actual C++ pointer/`unique_ptr` as a member, and give Rust full ownership of the wrapper. This adds a level of indirection, but it means all of the aliasing pointers are in C++ code, which means the usual lax C++ rules apply.

**Comment by adetaylor** [comment] 2022-08-15 14:20
I have good news and bad news here.

The good news is that I have made some progress here already. The bad news is that it's a minefield.

See the last paragraph [of this page](https://docs.rs/autocxx/latest/autocxx/macro.safety.html) about `unsafe_references_wrapped`. If you enable this mode, you should get:

```rust
fn is_global(self: CppRef<Self>) -> bool
```

where `CppRef` is a reference that allows aliasing.

Isn't that marvellous?

No it isn't! For the following reasons:

* this is very early support and probably doesn't work with 99.9% of real code. There is a toy example in `examples/reference-wrappers`.
* it's such early support that its known problems aren't even recorded as bugs. (Also, I do not know what they are, so I guess they're unknown knowns...)
* internally it still briefly uses a reference, though I hope we can solve that in due course. This is because pointers are not yet allowed as method receivers, though there is some discussion that this might be allowed in future. (Next step is for someone to write an RFC here).

So this is all a bit of a disaster zone at the moment, and I would _love_ contributions here. This is technically a duplicate of #1006 where this was added.

One specific confession: we've made things worse here than with `cxx`. With cxx, this UB only occurs with trivial (non-opaque) types. That's because cxx's opaque types are zero-sized and you can't have aliasing UB with zero-sized types. In order to support stack allocation, autocxx makes even opaque types sized and thus this UB occurs with both POD and non-POD types. (I'd accept a PR to add a mode to make non-POD types ZSTs again).

**Closed by adetaylor** 2022-08-15 14:20 UTC

**Comment by bsilver8192** [comment] 2022-08-15 19:19
Good to know that work is intended to address this use case. Any thoughts on having a mode that generates methods as free functions to avoid the intermediate Rust references before arbitrary self types are stable?

Also, I don't think the comments in [reference_wrappers](https://github.com/google/autocxx/blob/8a9f5fd6dc41bd9afc2862c70de9065af61789ec/src/reference_wrapper.rs) are correct. The proposed Rust aliasing models I've seen consider C++ references the same as C/C++ pointers, which very much do have implications for Rust. It's not just modifying objects through other pointers that's restricted, reading from them is also disallowed while a Rust mutable reference exists.

There are also restrictions around how the pointers/C++ references/Rust reference are derived, but I'm not sure there's as much consensus there.

**Comment by adetaylor** [comment] 2022-08-16 13:44
> I don't think the comments in [reference_wrappers](https://github.com/google/autocxx/blob/8a9f5fd6dc41bd9afc2862c70de9065af61789ec/src/reference_wrapper.rs) are correct

Which specific bit of comments?

> It's not just modifying objects through other pointers that's restricted, reading from them is also disallowed while a Rust mutable reference exists.

Yes, the intention is that there can _either_ be C++ references/pointers _or_ Rust references, never both. If this mode is enabled, references are returned from C++ as `CppRef`s rather than Rust references, so there can never be a Rust reference to a C++ thing (without use of `unsafe`). Meanwhile C++ references can only be made to Rust data if it's imprisoned in a `CppPin`. So the intent indeed matches what you say, but the comments might be outdated.

> Any thoughts on having a mode that generates methods as free functions to avoid the intermediate Rust references before arbitrary self types are stable?

Hm. I don't think I _specifically_ object but it is pretty yucky. I think I'd be OK with such a contribution, but I personally would prefer to spend my time on trying to nudge forward the arbitrary self types work, because at the end of the day I feel that will be necessary to make all of this ergonomic.

**Comment by bsilver8192** [comment] 2022-08-16 23:29
> > I don't think the comments in [reference_wrappers](https://github.com/google/autocxx/blob/8a9f5fd6dc41bd9afc2862c70de9065af61789ec/src/reference_wrapper.rs) are correct
> 
> Which specific bit of comments?

For example on [CppMutRef::as_mut](https://github.com/google/autocxx/blob/8a9f5fd6dc41bd9afc2862c70de9065af61789ec/src/reference_wrapper.rs#L47):
```rust
    /// Callers must guarantee that the referent is not modified by any other
    /// C++ or Rust code while the returned reference exists. Callers must
    /// also guarantee that no other Rust reference is created to the referent
    /// while the returned reference exists.
```

I'm pretty sure that C++ reading from a variable while a Rust mutable reference exists is undefined behavior, which the comment explicitly excludes with the "is modified by" language.

This may also be undefined behavior, I'm not sure how the various proposals for a Rust aliasing model treat it:
1. Have a Rust or C++ reference
2. Create a C++ pointer from 1
3. Create a Rust unique reference from 1, then drop it
4. Read and/or write using the C++ pointer from 2
