### ISSUE TITLE
Mismatch in size of std::string

### ISSUE THREAD

**Issue by dtolnay** [google/autocxx#19] opened 2020-10-11 01:12 UTC
On my machine this input header results in the following generated Rust struct, which looks reasonable, except the Rust side and C++ side disagree about the size of std::string.

```cpp
#pragma once
#include <cstdint>
#include <string>
struct S {
  explicit S(uint32_t i);
  std::string s;
  uint32_t i;
};
```

```rust
// generated by autocxx:

#[repr(C)]
pub struct S {
    pub s: ::cxx::CxxString,
    pub __bindgen_padding_0: [u32; 6usize],
    pub i: u32,
}
```

I'll share a PR to help reproduce. Possibly bindgen run by autocxx is finding a different set of system headers than the C++ build?

Here is the debug printing I used to confirm the issue:

```cpp
S::S(uint32_t i) : i(i) {
  std::cout << "C++:" << (size_t(&this->i) - size_t(this)) << std::endl;
}
```

```rust
let s = ffi::cxxbridge::S_make_unique(1);
println!("Rust:{}", (&s.i as *const _ as usize) - (&*s as *const _ as usize));
println!("{}", s.i);
```

Expected output is that C++ and Rust print the same size and the third line is 1, but the actual output is:

```console
C++:32
Rust:24
0
```

**Comment by adetaylor** [comment] 2020-10-11 01:15
Per comments on #18 this is intentional because of [this prelude](https://github.com/google/autocxx/blob/main/engine/src/lib.rs#L118) without which bindgen can't cope with `std::string` at all (and, as you hint, different STLs could _theoretically_ give different implementations so we _probably_ can't make better assumptions - I must admit I have not checked the C++ standards though). I am going to treat this as a duplicate of #18, which remains in brief "field access to non-POD types is doomed"!!

**Closed by adetaylor** 2020-10-11 01:15 UTC

**Comment by dtolnay** [comment] 2020-10-11 01:23
Ah that's too bad. :( It would have been really slick to be able to support this without accessor methods. I have some ideas for how to make it work anyway without accessors and without requiring to know the field sizes at codegen time, which I will write up.
