### ISSUE TITLE
building the demo segfaults

### ISSUE THREAD

**Issue by Volker-Weissmann** [google/autocxx#168] opened 2021-01-05 17:29 UTC
Hello,

I initially reported this bug in the rustc repository, but since someone noted, that this bug has to do with the way you load llvm it might be a bug in autocxx, so I decided to tell you of the existance of this bug:

https://github.com/rust-lang/rust/issues/80725

**Comment by adetaylor** [comment] 2021-01-05 18:00
Thanks very much indeed for reporting this and doing the legwork.

Although autocxx doesn't itself use llvm, it does (boldly) attempt to use bindgen from within a procedural macro, and that seems unwise for a variety of reasons.

#51 is the plan to move away from that model. I will expedite! I may decided to close this as a duplicate of #51 but I'll keep it open for now.

**Comment by Volker-Weissmann** [comment] 2021-01-05 18:29
Thank xou for writing that patch.
Do you know of any Duct-Tape hotfix I can use to try out autocxx? Because I wrote a 2000 lines patch for bindgen and if autocxx does some things I suspect it does, then this patch is useless because autocxx already has the features my patch would add.

**Comment by adetaylor** [comment] 2021-01-05 19:57
I have not run into the llvm conflicts which you've seen, so it might be that you can use a slightly earlier version of rustc and maybe it will work?

But in any case - I'll aim to get #51 landed this week. No promises!

There's lots which is incomplete about autocxx - it's still early days - so your patch may still be useful. Also, see #124 for some of the ways in which bindgen doesn't quite do what we need.

**Comment by adetaylor** [comment] 2021-01-06 21:44
WIP towards fixing this here - https://github.com/google/autocxx/pull/171 - but it probably doesn't fix this issue yet, as it's likely that the procedural macro still links to llvm. Cargo cfg shenanigans will be used to avoid that. Also, the code is junk for now and will involve lots of cleanups and rebasing before I merge.

**Comment by Volker-Weissmann** [comment] 2021-01-07 00:21
In ed7a5a224d899abb020632baac14ff65f936d4b4 , cargo run in the demo folder works on my machine.

**Comment by adetaylor** [comment] 2021-01-07 01:02
Ah good, thanks for letting me know.

**Comment by adetaylor** [comment] 2021-01-07 01:29
Fixed by #171. I still need to do a little bit of cleanup, e.g. #173. In general this has been quite a big change so I anticipate quite a bit of tinkering ahead, but the macro should no longer do anything complex at all.

**Closed by adetaylor** 2021-01-07 01:29 UTC
