### ISSUE TITLE
The trait bound `CxxVector<u8>: ExternType` is not satisfied

### ISSUE THREAD

**Issue by zkjanus** [google/autocxx#569] opened 2021-06-14 13:55 UTC
Hello, I'm encountering a follow up problem of trying to reuse a type generated from autocxx in another cxxbridge. I couldn't reopen the old issue https://github.com/google/autocxx/issues/565.

I was thinking I needed to write implementations for ExternTypes made from bindgen as described here: https://cxx.rs/extern-c++.html#integrating-with-bindgen-generated-or-handwritten-unsafe-bindings but I could not get them to work. 

Possibly related issue? https://github.com/dtolnay/cxx/issues/313

## Expected Behavior

Type reused in second FFI successfully.

## Actual Behavior

```
error[E0277]: the trait bound `CxxVector<u8>: ExternType` is not satisfied
   --> gen/libbitcoin/src/main.rs:37:9

        type data = crate::ffi::libbitcoin::system::data_chunk;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `ExternType` is not implemented for `CxxVector<u8>`
```

## Steps to Reproduce the Problem

1.  Generate bindings using autocxx, like `generate!("libbitcoin::system::data_chunk")`, an alias to `std::vector<uint8_t>`
2.  Create a second `#[cxxbridge]`
3.  Use existing ffi type generated above in new bridge `type data_chunk = crate::ffi::libbitcoin::system::data_chunk;`

## Specifications

- Version: 0.11.0
- Platform: NixOS

**Comment by zkjanus** [comment] 2021-06-14 23:45
I'm pretty sure it's because `data_chunk` is an alias to `std::vector<uint8_t>`, and the ExternType isn't created for CxxVector<u8>

**Comment by adetaylor** [comment] 2021-06-18 04:33
Thanks for the report. I am away for a few days so will take a look in a while. However, I suspect this is not specific to autocxx and is equally applicable to using two interrelated bridges in cxx. I suspect you're right that CxxVector has no implementation of ExternType, and I suspect this is a fundamental constraint which can't easily be fixed. It would be worth coming up with a minimal case using cxx alone.

**Comment by zkjanus** [comment] 2021-06-19 18:42
I will try to use two `cxxbridge`s and a CxxVector type from the other, to see if the constraint exists there.

**Comment by adetaylor** [comment] 2021-06-25 21:19
Any progress? Did the constraint exist in cxx?

**Comment by zkjanus** [comment] 2021-06-30 20:22
I don't know if i'm doing it correctly, but it built successfully like this:
**file2.rs**
```
  #[cxx::bridge(namespace = "libbitcoin::system")]
  pub mod ffi {
  
      unsafe extern "C++" {
          include!("bitcoin/system.hpp");
  
          pub type data_chunk;
      }
  }
```
main.rs
```
  mod file2;
  
  #[cxx::bridge]
  pub mod ffi2 {
  
      unsafe extern "C++" {
          include!("helpers.hpp");
  
          #[namespace = "libbitcoin::system"]
          type data_chunk = crate::file2::ffi::data_chunk;
          //pub fn new_seed(seed: u8) -> data_chunk;
  
      }
  }
  fn main() {
  
  }

```

**Comment by adetaylor** [comment] 2021-07-04 05:35
The problem is specific to the use of a `CxxVector` from one bridge, being used as an `ExternType` from the other.

If you like, add the build output you get when running `RUST_LOG=autocxx_engine=info cargo build -vvv` so I can see the exact definition of `data_chunk` which `autocxx` generates.

**Comment by zkjanus** [comment] 2021-07-05 05:58
I have to run it as a `--release` because of this issue https://github.com/google/autocxx/issues/362
```
❯ RUST_LOG=autocxx_engine=info cargo build --release -p libbitcoin-rs -vvv
         Fresh cfg-if v1.0.0
         Fresh cxxbridge-flags v1.0.49
         Fresh unicode-segmentation v1.7.1
         Fresh unicode-xid v0.2.2
         Fresh unicode-width v0.1.8
         Fresh unindent v0.1.7
         Fresh termcolor v1.1.2
         Fresh regex-syntax v0.6.25
         Fresh ppv-lite86 v0.2.10
         Fresh vec_map v0.8.2
         Fresh strsim v0.8.0
         Fresh glob v0.3.0
         Fresh ansi_term v0.11.0
         Fresh humantime v2.1.0
         Fresh either v1.6.1
         Fresh peeking_take_while v0.1.2
         Fresh rustc-hash v1.1.0
         Fresh lazy_static v1.4.0
         Fresh remove_dir_all v0.5.3
         Fresh lazycell v1.3.0
         Fresh shlex v1.0.0
         Fresh pkg-config v0.3.19
         Fresh version_check v0.9.3
         Fresh once_cell v1.7.2
         Fresh libloading v0.7.0
         Fresh itertools v0.9.0
         Fresh heck v0.3.2
         Fresh textwrap v0.11.0
         Fresh indoc v1.0.3
         Fresh codespan-reporting v0.11.1
         Fresh itertools v0.10.0
         Fresh libc v0.2.95
         Fresh proc-macro2 v1.0.27
         Fresh memchr v2.4.0
         Fresh bitflags v1.2.1
         Fresh getrandom v0.2.3
         Fresh atty v0.2.14
         Fresh jobserver v0.1.22
         Fresh which v3.1.1
         Fresh quote v1.0.9
         Fresh aho-corasick v0.7.18
         Fresh nom v5.1.2
         Fresh clang-sys v1.2.0
         Fresh rand_core v0.6.2
         Fresh clap v2.33.3
         Fresh proc-macro-error-attr v1.0.4
         Fresh syn v1.0.72
         Fresh cc v1.0.68
         Fresh regex v1.5.4
         Fresh cexpr v0.4.0
         Fresh rand_chacha v0.3.0
         Fresh ctor v0.1.20
         Fresh proc-macro-error v1.0.4
         Fresh cxxbridge-macro v1.0.49
         Fresh strum_macros v0.20.1
         Fresh unzip-n v0.1.2
         Fresh cxx-gen v0.7.49
         Fresh aquamarine v0.1.10
         Fresh value-bag v1.0.0-alpha.7
         Fresh rand v0.8.3
  warning: In file included from /nix/store/q8rv03yvqsfipnxwyj0sb6lqs50y5b3q-gcc-10.2.0/include/c++/10.2.0/x86_64-unknown-linux-gnu/bits/os_defines.h:39,
  warning:                  from /nix/store/q8rv03yvqsfipnxwyj0sb6lqs50y5b3q-gcc-10.2.0/include/c++/10.2.0/x86_64-unknown-linux-gnu/bits/c++config.h:518,
  warning:                  from /nix/store/q8rv03yvqsfipnxwyj0sb6lqs50y5b3q-gcc-10.2.0/include/c++/10.2.0/utility:68,
  warning:                  from /nix/store/q8rv03yvqsfipnxwyj0sb6lqs50y5b3q-gcc-10.2.0/include/c++/10.2.0/algorithm:60,
  warning:                  from src/../include/cxx.h:2,
  warning:                  from src/cxx.cc:1:
  warning: /nix/store/vr4977307zkjprfkivi4lgbzlvig3y9j-glibc-2.32-40-dev/include/features.h:397:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
  warning:   397 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
  warning:       |    ^~~~~~~
         Fresh link-cplusplus v1.0.5
         Fresh log v0.4.14
         Fresh tempfile v3.2.0
         Fresh env_logger v0.8.3
         Fresh cxx v1.0.49
         Fresh autocxx-parser v0.11.0
         Fresh autocxx-macro v0.11.0
         Fresh autocxx-bindgen v0.58.5
         Fresh autocxx-build v0.11.0
         Fresh autocxx-engine v0.11.0
         Fresh autocxx v0.11.0
  warning: In file included from /home/janus/src/autocxx-test/target/release/build/libbitcoin-rs-24788417da0fc0e6/out/autocxx-build-dir/cxx/gen1.cxx:2:
  warning: src/helpers.hpp: In function ‘std::unique_ptr<libbitcoin::system::wallet::hd_private> new_private_key(libbitcoin::system::data_chunk&)’:
  warning: src/helpers.hpp:6: warning: unused parameter ‘data’ [-Wunused-parameter]
  warning:     6 | std::unique_ptr<libbitcoin::system::wallet::hd_private> new_private_key(libbitcoin::system::data_chunk& data) {
  warning:       |
     Compiling libbitcoin-rs v0.1.0 (/home/janus/src/autocxx-test/gen/libbitcoin)
       Running `CARGO=/nix/store/aqi2ja56yk2g1k4rh6rfd2dca5sym875-cargo-1.51.0/bin/cargo CARGO_BIN_NAME=libbitcoin-rs CARGO_CRATE_NAME=libbitcoin_rs CARGO_MANIFEST_DIR=/home/janus/src/  autocxx-test/gen/libbitcoin CARGO_PKG_AUTHORS='Janus <janus@dark.fi>' CARGO_PKG_DESCRIPTION='' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE='' CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=lib  bitcoin-rs CARGO_PKG_REPOSITORY='' CARGO_PKG_VERSION=0.1.0 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=1 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION_PRE='' CARGO_PRIMARY_PACKAG  E=1 LD_LIBRARY_PATH='/home/janus/src/autocxx-test/target/release/deps:/nix/store/0dji194lx40hamj6r490r9x2gb3jsn6i-rust-default-1.51.0/lib:' OUT_DIR=/home/janus/src/autocxx-test/targe  t/release/build/libbitcoin-rs-24788417da0fc0e6/out rustc --crate-name libbitcoin_rs --edition=2018 gen/libbitcoin/src/main.rs --error-format=json --json=diagnostic-rendered-ansi --cr  ate-type bin --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no -C debuginfo=1 -C metadata=7a61ce45796b79ef -C extra-filename=-7a61ce45796b79ef --out-dir /home/janus/src/autocxx  -test/target/release/deps -L dependency=/home/janus/src/autocxx-test/target/release/deps --extern autocxx=/home/janus/src/autocxx-test/target/release/deps/libautocxx-1c036af47b672617  .rlib --extern cxx=/home/janus/src/autocxx-test/target/release/deps/libcxx-d19da5ec3c0bd4fc.rlib -L native=/nix/store/89wrygwxnf9rd72w3hc1m9j4gvl4v6s2-libbitcoin-4.0pre/lib -L native  =/nix/store/amna7v8bd0p3f4gj853ic3zivfp624bg-boost-1.75.0/lib -L native=/nix/store/hj0r4zh2k7nn4mlnf9bcswdk4hnympsl-secp256k1-libbitcoin-0.1.0.19/lib -L native=/nix/store/89wrygwxnf9  rd72w3hc1m9j4gvl4v6s2-libbitcoin-4.0pre/lib -L native=/nix/store/amna7v8bd0p3f4gj853ic3zivfp624bg-boost-1.75.0/lib -L native=/nix/store/hj0r4zh2k7nn4mlnf9bcswdk4hnympsl-secp256k1-lib  bitcoin-0.1.0.19/lib -L native=/nix/store/sminbb13mx4kxnmp92ghxlbww292924a-libbitcoin-client-4.0pre/lib -L native=/nix/store/5c49pxc0s3jkx8lx6lrnhi3rb7kkz0q4-libbitcoin-protocol-4.0p  re/lib -L native=/nix/store/bwkslqxhbhizm9xym97g7bxwwmajk8af-zeromq-4.3.4/lib -L native=/home/janus/src/autocxx-test/target/release/build/libbitcoin-rs-24788417da0fc0e6/out -L /nix/s  tore/89wrygwxnf9rd72w3hc1m9j4gvl4v6s2-libbitcoin-4.0pre/lib -L /nix/store/amna7v8bd0p3f4gj853ic3zivfp624bg-boost-1.75.0/lib -L /nix/store/hj0r4zh2k7nn4mlnf9bcswdk4hnympsl-secp256k1-l  ibbitcoin-0.1.0.19/lib -L /nix/store/89wrygwxnf9rd72w3hc1m9j4gvl4v6s2-libbitcoin-4.0pre/lib -L /nix/store/amna7v8bd0p3f4gj853ic3zivfp624bg-boost-1.75.0/lib -L /nix/store/hj0r4zh2k7nn  4mlnf9bcswdk4hnympsl-secp256k1-libbitcoin-0.1.0.19/lib -L /nix/store/sminbb13mx4kxnmp92ghxlbww292924a-libbitcoin-client-4.0pre/lib -L /nix/store/5c49pxc0s3jkx8lx6lrnhi3rb7kkz0q4-libb  itcoin-protocol-4.0pre/lib -L /nix/store/bwkslqxhbhizm9xym97g7bxwwmajk8af-zeromq-4.3.4/lib -l bitcoin-system -l boost_chrono -l boost_date_time -l boost_filesystem -l boost_iostreams   -l boost_locale -l boost_log -l boost_program_options -l boost_regex -l boost_system -l boost_thread -l pthread -l rt -l dl -l secp256k1 -l bitcoin-client -l bitcoin-protocol -l zmq   -l bitcoin-system -l boost_chrono -l boost_date_time -l boost_filesystem -l boost_iostreams -l boost_locale -l boost_log -l boost_program_options -l boost_regex -l boost_system -l b  oost_thread -l pthread -l rt -l dl -l secp256k1 -l static=libbitcoin-rs -l stdc++ -l bitcoin-system -l boost_chrono -l boost_date_time -l boost_filesystem -l boost_iostreams -l boost  _locale -l boost_log -l boost_program_options -l boost_regex -l boost_system -l boost_thread -l pthread -l rt -l dl -l secp256k1 -l bitcoin-client -l bitcoin-protocol -l zmq -l bitco  in-system -l boost_chrono -l boost_date_time -l boost_filesystem -l boost_iostreams -l boost_locale -l boost_log -l boost_program_options -l boost_regex -l boost_system -l boost_thre  ad -l pthread -l rt -l dl -l secp256k1 -L native=/home/janus/src/autocxx-test/target/release/build/cxx-9e4cde8b56d41a0f/out -L native=/home/janus/src/autocxx-test/target/release/buil  d/link-cplusplus-f405a3ab9bce93a3/out`
  warning: unused imports: `path::PathBuf`, `pin::Pin`
   --> gen/libbitcoin/src/main.rs:4:5
    |
  4 |     pin::Pin,
    |     ^^^^^^^^
  5 |     path::PathBuf,
    |     ^^^^^^^^^^^^^
    |
    = note: `#[warn(unused_imports)]` on by default
   
  warning: unused imports: `ExternType`, `type_id`
   --> gen/libbitcoin/src/main.rs:7:11
    |
  7 | use cxx::{type_id, ExternType};
    |           ^^^^^^^  ^^^^^^^^^^
   
  error[E0277]: the trait bound `CxxVector<u8>: ExternType` is not satisfied
     --> gen/libbitcoin/src/main.rs:38:9
      |
  38  |         type data_chunk = crate::ffi::libbitcoin::system::data_chunk;
      |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `ExternType` is not implemented for `CxxVector<u8>`
      |
     ::: /home/janus/.cargo/registry/src/github.com-1ecc6299db9ec823/cxx-1.0.49/src/extern_type.rs:183:30
      |
  183 | pub fn verify_extern_type<T: ExternType<Id = Id>, Id>() {}
      |                              ------------------- required by this bound in `verify_extern_type`
   
  error: aborting due to previous error; 2 warnings emitted
   
  For more information about this error, try `rustc --explain E0277`.
  The following warnings were emitted during compilation:
   
  warning: In file included from /home/janus/src/autocxx-test/target/release/build/libbitcoin-rs-24788417da0fc0e6/out/autocxx-build-dir/cxx/gen1.cxx:2:
  warning: src/helpers.hpp: In function ‘std::unique_ptr<libbitcoin::system::wallet::hd_private> new_private_key(libbitcoin::system::data_chunk&)’:
  warning: src/helpers.hpp:6: warning: unused parameter ‘data’ [-Wunused-parameter]
  warning:     6 | std::unique_ptr<libbitcoin::system::wallet::hd_private> new_private_key(libbitcoin::system::data_chunk& data) {
  warning:       |
   
  error: could not compile `libbitcoin-rs`
   
  Caused by:
    process didn't exit successfully: `CARGO=/nix/store/aqi2ja56yk2g1k4rh6rfd2dca5sym875-cargo-1.51.0/bin/cargo CARGO_BIN_NAME=libbitcoin-rs CARGO_CRATE_NAME=libbitcoin_rs CARGO_MANIFE  ST_DIR=/home/janus/src/autocxx-test/gen/libbitcoin CARGO_PKG_AUTHORS='Janus <janus@dark.fi>' CARGO_PKG_DESCRIPTION='' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE='' CARGO_PKG_LICENSE_FIL  E='' CARGO_PKG_NAME=libbitcoin-rs CARGO_PKG_REPOSITORY='' CARGO_PKG_VERSION=0.1.0 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=1 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION_PRE=  '' CARGO_PRIMARY_PACKAGE=1 LD_LIBRARY_PATH='/home/janus/src/autocxx-test/target/release/deps:/nix/store/0dji194lx40hamj6r490r9x2gb3jsn6i-rust-default-1.51.0/lib:' OUT_DIR=/home/janus  /src/autocxx-test/target/release/build/libbitcoin-rs-24788417da0fc0e6/out rustc --crate-name libbitcoin_rs --edition=2018 gen/libbitcoin/src/main.rs --error-format=json --json=diagno  stic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no -C debuginfo=1 -C metadata=7a61ce45796b79ef -C extra-filename=-7a61ce45796b79ef --out-dir   /home/janus/src/autocxx-test/target/release/deps -L dependency=/home/janus/src/autocxx-test/target/release/deps --extern autocxx=/home/janus/src/autocxx-test/target/release/deps/liba  utocxx-1c036af47b672617.rlib --extern cxx=/home/janus/src/autocxx-test/target/release/deps/libcxx-d19da5ec3c0bd4fc.rlib -L native=/nix/store/89wrygwxnf9rd72w3hc1m9j4gvl4v6s2-libbitco  in-4.0pre/lib -L native=/nix/store/amna7v8bd0p3f4gj853ic3zivfp624bg-boost-1.75.0/lib -L native=/nix/store/hj0r4zh2k7nn4mlnf9bcswdk4hnympsl-secp256k1-libbitcoin-0.1.0.19/lib -L native  =/nix/store/89wrygwxnf9rd72w3hc1m9j4gvl4v6s2-libbitcoin-4.0pre/lib -L native=/nix/store/amna7v8bd0p3f4gj853ic3zivfp624bg-boost-1.75.0/lib -L native=/nix/store/hj0r4zh2k7nn4mlnf9bcswd  k4hnympsl-secp256k1-libbitcoin-0.1.0.19/lib -L native=/nix/store/sminbb13mx4kxnmp92ghxlbww292924a-libbitcoin-client-4.0pre/lib -L native=/nix/store/5c49pxc0s3jkx8lx6lrnhi3rb7kkz0q4-l  ibbitcoin-protocol-4.0pre/lib -L native=/nix/store/bwkslqxhbhizm9xym97g7bxwwmajk8af-zeromq-4.3.4/lib -L native=/home/janus/src/autocxx-test/target/release/build/libbitcoin-rs-2478841  7da0fc0e6/out -L /nix/store/89wrygwxnf9rd72w3hc1m9j4gvl4v6s2-libbitcoin-4.0pre/lib -L /nix/store/amna7v8bd0p3f4gj853ic3zivfp624bg-boost-1.75.0/lib -L /nix/store/hj0r4zh2k7nn4mlnf9bcs  wdk4hnympsl-secp256k1-libbitcoin-0.1.0.19/lib -L /nix/store/89wrygwxnf9rd72w3hc1m9j4gvl4v6s2-libbitcoin-4.0pre/lib -L /nix/store/amna7v8bd0p3f4gj853ic3zivfp624bg-boost-1.75.0/lib -L   /nix/store/hj0r4zh2k7nn4mlnf9bcswdk4hnympsl-secp256k1-libbitcoin-0.1.0.19/lib -L /nix/store/sminbb13mx4kxnmp92ghxlbww292924a-libbitcoin-client-4.0pre/lib -L /nix/store/5c49pxc0s3jkx8  lx6lrnhi3rb7kkz0q4-libbitcoin-protocol-4.0pre/lib -L /nix/store/bwkslqxhbhizm9xym97g7bxwwmajk8af-zeromq-4.3.4/lib -l bitcoin-system -l boost_chrono -l boost_date_time -l boost_filesy  stem -l boost_iostreams -l boost_locale -l boost_log -l boost_program_options -l boost_regex -l boost_system -l boost_thread -l pthread -l rt -l dl -l secp256k1 -l bitcoin-client -l   bitcoin-protocol -l zmq -l bitcoin-system -l boost_chrono -l boost_date_time -l boost_filesystem -l boost_iostreams -l boost_locale -l boost_log -l boost_program_options -l boost_reg  ex -l boost_system -l boost_thread -l pthread -l rt -l dl -l secp256k1 -l static=libbitcoin-rs -l stdc++ -l bitcoin-system -l boost_chrono -l boost_date_time -l boost_filesystem -l b  oost_iostreams -l boost_locale -l boost_log -l boost_program_options -l boost_regex -l boost_system -l boost_thread -l pthread -l rt -l dl -l secp256k1 -l bitcoin-client -l bitcoin-p  rotocol -l zmq -l bitcoin-system -l boost_chrono -l boost_date_time -l boost_filesystem -l boost_iostreams -l boost_locale -l boost_log -l boost_program_options -l boost_regex -l boo  st_system -l boost_thread -l pthread -l rt -l dl -l secp256k1 -L native=/home/janus/src/autocxx-test/target/release/build/cxx-9e4cde8b56d41a0f/out -L native=/home/janus/src/autocxx-t  est/target/release/build/link-cplusplus-f405a3ab9bce93a3/out` (exit code: 1)
```

**Comment by adetaylor** [comment] 2021-11-22 00:57
Unfortunately those logs are incomplete - maybe you need to `touch` some files to get it to regenerate everything, or similar. Either way, please come up with a minimized test case so that I can reproduce this. The ideal is that you make a pull request against autocxx containing a new test in `integration-tests/src/tests.rs`. But a standalone repo with a *complete* and *minimal* example would be fine too. Please make sure it builds without any external dependencies - see [https://github.com/google/autocxx#reporting-bugs](reporting bugs). I'll close this for now, but if you can provide that I'll be happy to take a look.

**Closed by adetaylor** 2021-11-22 00:57 UTC
