### ISSUE TITLE
customize derive

### ISSUE THREAD

**Issue by yshui** [google/autocxx#1189] opened 2022-11-12 23:07 UTC
Is it possible to customize what traits are derived for generated types? The builder doesn't seem to have an option for this.

**Comment by adetaylor** [comment] 2022-11-14 12:59
Duplicate of #668!

**Closed by adetaylor** 2022-11-14 12:59 UTC

**Comment by yshui** [comment] 2022-11-14 15:08
:rofl: wait, it was opened by me!

**Comment by adetaylor** [comment] 2022-11-14 15:12
:)))
