### ISSUE TITLE
Calling superclass methods

### ISSUE THREAD

**Issue by steeve** [google/autocxx#725] opened 2022-01-02 17:05 UTC
## Expected Behavior

Call super class/struct methods from child class.

## Actual Behavior

Consider this code:
```c++
#include <cstdint>

struct A {
    A() {}

    uint32_t foo(uint32_t a) {
        return a+1;
    };
};

struct B : A {
    B() {}
};
```

```rust
use autocxx::include_cpp;

autocxx::include_cpp! {
    #include "sample.hpp"
    generate!("A")
    generate!("B")
    safety!(unsafe)
}
```

The generated code is:
```rust
    mod bindgen {
        pub(super) mod root {
            pub use cxxbridge::A;
            pub use cxxbridge::B;
            impl B {
                pub fn make_unique() -> cxx::UniquePtr<root::B> {
                    cxxbridge::B_make_unique_autocxx_wrapper()
                }
            }
            impl A {
                pub fn make_unique() -> cxx::UniquePtr<root::A> {
                    cxxbridge::make_unique_autocxx_wrapper()
                }
            }
            #[allow(unused_imports)]
            use self::super::super::cxxbridge;
            #[allow(unused_imports)]
            use self::super::super::ToCppString;
            #[allow(unused_imports)]
            use self::super::root;
        }
    }
    #[cxx::bridge]
    mod cxxbridge {
        unsafe extern "C++" {
            fn autocxx_make_string_default(str_: &str) -> UniquePtr<CxxString>;
            type A;
            type B;
            pub fn foo(self: Pin<&mut A>, a: u32) -> u32;
            pub fn make_unique_autocxx_wrapper() -> UniquePtr<A>;
            pub fn B_make_unique_autocxx_wrapper() -> UniquePtr<B>;
            include!("sample.hpp");
            include!("autocxxgen_ffi.h");
        }
        extern "Rust" {}
    }
```

The code was generated with:
```
$ autocxx-gen sample.rs --gen-rs-complete --gen-cpp --outdir sample/
```

Observations:
1. while `foo` is properly generated, it is not generated inside `impl A` unless it's marked `virtual`
2. it's not possible to call `B.foo()`

## Specifications

- Version: `1.0.61`
- Platform: `aarch64-apple`

Thanks again for this very promising project!

**Comment by adetaylor** [comment] 2022-01-02 18:09
Thanks. Relates to #592,

**Comment by steeve** [comment] 2022-01-02 20:56
@adetaylor thank you for the (very) fast reply! Didn't you say you wanted to keep this open though?

**Comment by steeve** [comment] 2022-01-02 20:57
I see that #197 has a test that seems ignored though, at https://github.com/google/autocxx/blob/efb2d86284a2445bbfbf1840c9634f20e17fec05/integration-tests/src/tests.rs#L3788

Which got me confused :)

**Comment by adetaylor** [comment] 2022-01-03 01:32
Thanks again! OK, I took a more thorough look at your report based on your discovery of a relevant-seeming ignored test case.

Regarding:
> while `foo` is properly generated, it is not generated inside `impl A` unless it's marked virtual

That's not in fact correct. `cxx` itself will put it inside an `impl A` block, so if you had an instance of `A`, you would indeed be able to call `my_a_instance.foo()`.

(As you've noticed, we do this within autocxx generated code for _virtual_ functions, because cxx can't support this natively. But for non-virtual functions, it can, and the net behavior should be the same.)

So the problem is:
> it's not possible to call `B.foo()`

and yeah, it's a fair cop :) We don't support this yet.

And you're also right that there's an ignored test case for this. The difference in your report is that #197 was specifically about _virtual_ functions being callable on derived classes, but you're right, that really makes no difference, and the existing test case should do the trick.

Therefore: I think I'm going to regard this as a duplicate of #197 after all.

**Closed by adetaylor** 2022-01-03 01:32 UTC

**Comment by steeve** [comment] 2022-01-03 06:19
Super clear, thank you!
