### ISSUE TITLE
Debug assertion hit in `autocxx-bindgen-0.57.3/src/ir/context.rs:716:13`

### ISSUE THREAD

**Issue by thomaseizinger** [google/autocxx#362] opened 2021-04-13 08:10 UTC
## Expected Behavior

Not hitting any debug assertions while running autocxx.

## Actual Behavior

```
thread 'main' panicked at 'assertion failed: `(left == right)`
    left: `Some(TypeId(ItemId(421934)))`,
   right: `None`', /home/thomas/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.57.3/src/ir/context.rs:716:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Steps to Reproduce the Problem

1. Clone https://github.com/thomaseizinger/monero-wallet-sys
1. Checkout commit `1f3e4eaba679a33b656ae27464f8b2e972b4c38e` (that is the last one at the time of writing)
1. Run `cargo build`

## Specifications

- Version: 0.5.4
- Platform: Linux / Manjaro

**Comment by adetaylor** [comment] 2021-04-13 17:42
Per my comments on #361, it'd be fantastic if you can give me a preprocessed header file that reproduces this, as I struggled with dependencies in getting your example to build. I don't know of any pre-existing bug which explains this so it would be much appreciated.

**Comment by thomaseizinger** [comment] 2021-04-13 21:25
Thank you for the fast reply!

I read those instructions but unfortunately, I wasn't quite sure how I'd figure out, which header file causes the problem :/

Any pointers in how I should start?

Worst case, I can make you a Docker container for building everything. That should get rid of the dependency problem!

**Comment by thomaseizinger** [comment] 2021-04-14 00:58
I managed to get some more log output, here is the raw dump for now. Still analyzing this!

```
cargo:warning=MESSAGE:BindgenContext::add_item(Item { id: ItemId(421929), local_id: LazyCell { inner: UnsafeCell }, next_child_local_id: Cell { value: 1 }, canonical_name: LazyCell { inner: UnsafeCell }, path_for_allowlisting: LazyCell { inner: UnsafeCell }, comment: None, annotations: Annotations { opaque: false, hide: false, use_instead_of: None, disallow_copy: false, disallow_debug: false, disallow_default: false, private_fields: None, accessor_kind: None, constify_enum_variant: false, derives: [] }, parent_id: ItemId(0), kind: Type(Type { name: Some("context"), layout: Some(Layout { size: 24, align: 8, packed: false }), kind: Comp(CompInfo { kind: Struct, fields: BeforeComputingBitfieldUnits([RawField(FieldData { name: Some("key_"), ty: TypeId(ItemId(422000)), comment: None, annotations: Annotations { opaque: false, hide: false, use_instead_of: None, disallow_copy: false, disallow_debug: false, disallow_default: false, private_fields: None, accessor_kind: None, constify_enum_variant: false, derives: [] }, bitfield_width: None, public: false, offset: Some(0) }), RawField(FieldData { name: Some("value_"), ty: TypeId(ItemId(422002)), comment: None, annotations: Annotations { opaque: false, hide: false, use_instead_of: None, disallow_copy: false, disallow_debug: false, disallow_default: false, private_fields: None, accessor_kind: None, constify_enum_variant: false, derives: [] }, bitfield_width: None, public: false, offset: Some(64) }), RawField(FieldData { name: Some("next_"), ty: TypeId(ItemId(422004)), comment: None, annotations: Annotations { opaque: false, hide: false, use_instead_of: None, disallow_copy: false, disallow_debug: false, disallow_default: false, private_fields: None, accessor_kind: None, constify_enum_variant: false, derives: [] }, bitfield_width: None, public: false, offset: Some(128) })]), template_params: [], methods: [Method { kind: Normal, signature: FunctionId(ItemId(421999)), is_const: true }], constructors: [FunctionId(ItemId(421976)), FunctionId(ItemId(421986))], destructor: Some((Destructor, FunctionId(ItemId(421992)))), base_members: [Base { ty: TypeId(ItemId(421930)), kind: Normal, field_name: "_base", is_pub: false }], inner_types: [], inner_vars: [], has_own_virtual_method: false, has_destructor: true, has_nonempty_base: false, has_non_type_template_params: false, packed_attr: false, found_unknown_attr: false, is_forward_declaration: false }), is_const: false }) }, declaration: Some(Cursor(context kind: ClassDecl, loc: /usr/include/boost/asio/detail/call_stack.hpp:35:9, usr: Some("c:@N@boost@N@asio@N@detail@S@call_stack>#$@N@boost@N@asio@N@detail@S@thread_context#$@N@boost@N@asio@N@detail@S@thread_info_base@S@context"))), loc: Some(Cursor(value_ kind: VarDecl, loc: /usr/include/boost/asio/detail/keyword_tss_ptr.hpp:62:50, usr: Some("c:@N@boost@N@asio@N@detail@S@keyword_tss_ptr>#$@N@boost@N@asio@N@detail@S@call_stack>#$@N@boost@N@asio@N@detail@S@thread_context#$@N@boost@N@asio@N@detail@S@thread_info_base@S@context@value_")))
  cargo:warning=MESSAGE:add_item_to_module: adding ItemId(421929) as child of parent module ItemId(0)
  thread 'main' panicked at 'assertion failed: `(left == right)`
    left: `Some(TypeId(ItemId(421934)))`,
   right: `None`', autocxx-bindgen/src/ir/context.rs:721:13
```

**Comment by adetaylor** [comment] 2021-04-14 01:05
Thanks, but I really want the preprocessed output. (Because `creduce` is basically a miracle worker. It can take megabytes of incomprehensible C++ and reduce it to a few lines of test case. I _really_ don't want to wade through a million lines of boost.) I've raised #369 to add some better instructions to the `README` about how to actually to do the preprocessing.

**Comment by thomaseizinger** [comment] 2021-04-14 01:58
I tried to reduce the test case down to the essential C++ code but failed unfortunately. I also think I know why. From looking at the error message, the error already happens within `bindgen`. Hence, unless I misunderstand something, autocxx can actually never do its magic because we don't get that far :/

I think the CPP files bindgen is choking on are:

- `/usr/include/boost/asio/detail/keyword_tss_ptr.hpp`
- `/usr/include/boost/asio/detail/call_stack.hpp`

These contain a lot of templating so I am not surprised it causes problems given the warning in the README!

Given that it is only a debug assertion, I can work around this by compiling in release mode. If I do that, I eventually get stuck on https://github.com/google/autocxx/issues/266. It seems https://github.com/google/autocxx/pull/365 didn't quite fix https://github.com/google/autocxx/issues/364. I'll comment over there to keep the discussion separate.

**Comment by adetaylor** [comment] 2021-04-14 05:11
Please could you take a look at #372? I added a mode which should automatically dump the preprocessed output. It doesn't seem to be working quite properly for me - it didn't inline the contents of `<cstdint>` in my testing. Maybe that header is special. Still digging into it.

**Comment by thomaseizinger** [comment] 2021-04-14 05:25
I ran `AUTOCXX_PREPROCESS=output.h cargo build` using the code in #372 but I don't think the output is what you want.

<details>
<summary>output.h</summary>

```c
# 1 "/tmp/.tmponGTa9"
# 1 "<built-in>"
# 1 "<command-line>"
# 31 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4

# 1 "/usr/include/stdc-predef.h" 3 4
/* Copyright (C) 1991-2021 Free Software Foundation, Inc.
   This file is part of the GNU C Library.

   The GNU C Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   The GNU C Library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with the GNU C Library; if not, see
   <https://www.gnu.org/licenses/>.  */




/* This header is separate from features.h so that the compiler can
   include it implicitly at the start of every compilation.  It must
   not itself include <features.h> or any other header that includes
   <features.h> because the implicit include comes before any feature
   test macros that may be defined in a source file before it first
   explicitly includes a system header.  GCC knows the name of this
   header in order to preinclude it.  */

/* glibc's intent is to support the IEC 559 math functionality, real
   and complex.  If the GCC (4.9 and later) predefined macros
   specifying compiler intent are available, use them to determine
   whether the overall intent is to support these features; otherwise,
   presume an older compiler has intent to support these features and
   define these macros by default.  */
# 52 "/usr/include/stdc-predef.h" 3 4
/* wchar_t uses Unicode 10.0.0.  Version 10.0 of the Unicode Standard is
   synchronized with ISO/IEC 10646:2017, fifth edition, plus
   the following additions from Amendment 1 to the fifth edition:
   - 56 emoji characters
   - 285 hentaigana
   - 3 additional Zanabazar Square characters */
# 32 "<command-line>" 2
# 1 "/tmp/.tmponGTa9"

# 1 "/tmp/.tmponGTa9"
/*
autocxx config:

IncludeCppConfig { inclusions: [Header("wallet/wallet2.h")], exclude_utilities: false, unsafe_policy: AllFunctionsSafe, type_config: TypeConfig { pod_requests: [], allowlist: ["tools::wallet2", "make_string"], blocklist: [] }, parse_only: false }

end autocxx config.
autocxx preprocessed input:
*/

/**
* <div rustbindgen="true" replaces="std::vector">
*/
template<typename T> class CxxVector {
    T* ptr;
};


/**
* <div rustbindgen="true" replaces="std::shared_ptr">
*/
template<typename T> class SharedPtr {
    T* ptr;
};


/**
* <div rustbindgen="true" replaces="std::unique_ptr">
*/
template<typename T> class UniquePtr {
    T* ptr;
};


/**
* <div rustbindgen="true" replaces="rust::String">
*/
class String {
    char* ptr;
};


/**
* <div rustbindgen="true" replaces="rust::Str">
*/
class str {
    char* ptr;
};


/**
* <div rustbindgen="true" replaces="std::string">
*/
class CxxString {
    char* ptr;
};



# 1 "depend/monero/src/wallet/wallet2.h" 1
// Copyright (c) 2014-2020, The Monero Project
// 
// All rights reserved.
// 
// Redistribution and use in source and binary forms, with or without modification, are
// permitted provided that the following conditions are met:
// 
// 1. Redistributions of source code must retain the above copyright notice, this list of
//    conditions and the following disclaimer.
// 
// 2. Redistributions in binary form must reproduce the above copyright notice, this list
//    of conditions and the following disclaimer in the documentation and/or other
//    materials provided with the distribution.
// 
// 3. Neither the name of the copyright holder nor the names of its contributors may be
//    used to endorse or promote products derived from this software without specific
//    prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
// THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
// STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
// THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
// 
// Parts of this file are originally copyright (c) 2012-2013 The Cryptonote developers

       
```
</details>

**Comment by adetaylor** [comment] 2021-04-15 00:35
OK, I think the preprocessing stuff now works. See #369. Please give it a try!

**Comment by adetaylor** [comment] 2021-04-17 01:13
@thomaseizinger It'd be great to get the preprocessed file from you - thanks!

**Comment by thomaseizinger** [comment] 2021-04-17 01:38
Got caught up in something, sorry!

Will give it a crack later!

**Comment by thomaseizinger** [comment] 2021-04-17 04:17
I had to apply a little patch because apparently there is some non-UTF8 stuff in the C++ code so I hit a panic:

```patch
diff --git a/engine/src/lib.rs b/engine/src/lib.rs
index 2608962..a589695 100644
--- a/engine/src/lib.rs
+++ b/engine/src/lib.rs
@@ -505,7 +505,7 @@ pub fn preprocess(
     cmd.args(make_clang_args(incs, extra_clang_args));
     cmd.arg(listing_path.to_str().unwrap());
     let output = cmd.output().expect("failed to preprocess").stdout;
-    let output = std::str::from_utf8(&output).unwrap();
+    let output = unsafe { std::str::from_utf8_unchecked(&output) };
     let mut file = File::create(preprocess_path)?;
     for line in output.lines() {
         file.write_all(line.as_bytes())?;
```

So with this, it spits out a 20MB header file!
I tried to run `autocxx-reduce` on it but wasn't quite sure what `--problem` I should be specifying given that the debug_assert is hit within `autocxx-bindgen` :/

Anyway, [here](https://github.com/google/autocxx/files/6328615/output.h.zip) is the file! Hope you can make something useful out of it :)

**Comment by adetaylor** [comment] 2021-04-17 05:40
Thanks! First, I've applied your patch (or something similar) in #386, and fixed a bug in `autocxx-reduce` at the same time.

Secondly, my Linux box is now engaged in running `creduce` to make your 20MB of C++ smaller. As it requires the debug version of `autocxx-bindgen`, each iteration is taking several seconds, so I predict this may take 2-3 days.

Cheers!

**Comment by thomaseizinger** [comment] 2021-04-18 22:44
Not sure how well it is going with the debug build but to speed things up, I guess you could temporarily patch the `autocxx-bindgen` to `assert!` instead of `debug_assert!` and use a release build?

Alternatively, you may also be able to enable the `debug_assertions` cfg while doing a release build?

https://doc.rust-lang.org/std/macro.debug_assert.html#uses suggests that this is possible!

**Comment by adetaylor** [comment] 2021-04-18 22:46
It's fine - last time I checked it had eliminated 41% of the C++. It'll get there!

**Comment by adetaylor** [comment] 2021-04-20 15:12
62.2%... debug builds are _slow_

**Comment by adetaylor** [comment] 2021-04-20 15:13
(but I'm still just going to leave it to it, instead of faffing around enabling debug assertions in release mode)

**Comment by adetaylor** [comment] 2021-04-24 23:44
Finally got there! The minimized case is quite big.

```rust
namespace {
namespace {
namespace {
template <typename a> class b {
public:
  operator a *() { c; }
  static __thread a *c;
};
template <typename a> __thread a *b<a>::c;
template <typename a> class d : public b<a> {};
template <typename e, typename f> class g {
public:
  class context {
  public:
    context();
    e c;
  };
  static f *contains() {
    context *elem = h;
    elem->c;
  }
  static d<context> h;
};
class i;
class j {
public:
  typedef g<j, i> k;
};
class l : j {
  ~l();
};
l::~l() { k::contains; }
} // namespace
} // namespace
} // namespace
```

I have yet to dig into this at all (e.g. see if it reproduces with standalone bindgen, or with up-to-date bindgen), but I will.

**Comment by adetaylor** [comment] 2021-04-25 16:03
OK, this reproduces with upstream bindgen - reported as https://github.com/rust-lang/rust-bindgen/issues/2039 and I'll close this issue.

**Closed by adetaylor** 2021-04-25 16:03 UTC
Labels: bug

**Comment by thomaseizinger** [comment] 2021-04-26 00:17
Thank you! Subscribed to the upstream issue :)
